FROM node:18

WORKDIR /home/ubuntu/main/chat360
COPY /package.json /home/ubuntu/main/chat360
RUN npm i --legacy-peer-deps
COPY . /home/ubuntu/main/chat360
EXPOSE 3000
RUN npm run build
RUN bash deploy/upload.sh
ENTRYPOINT npm run start
