FROM node:18
RUN apt-get -y install curl unzip 
RUN	curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN	unzip awscliv2.zip && ./aws/install

WORKDIR /home/ubuntu/main/chat360
COPY /package.json /home/ubuntu/main/chat360
RUN npm i --legacy-peer-deps
COPY . /home/ubuntu/main/chat360
EXPOSE 3000
RUN npm run build
RUN bash deploy/upload.sh
ENTRYPOINT npm run start
